adding new changes

diff --git a/.github/workflows/dev-environment.yaml b/.github/workflows/dev-environment.yaml
--- a/.github/workflows/dev-environment.yaml
+++ b/.github/workflows/dev-environment.yaml
@@ -34,6 +34,14 @@ jobs:
             pip3 install pycodestyle    
             pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 && echo -e "\033[32mLint Checking Passed\033[0m"
             deactivate
+      - name: Check Pycodestyle output
+        run: |
+            pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 && echo -e "\033[32mLint Checking Passed\033[0m" > pycodestyle_output.txt
+            if [ -s pycodestyle_output.txt ]; then
+            echo "Pycodestyle errors found:"
+            cat pycodestyle_output.txt
+            exit 1
+            fi
       - name: python unit tests
         run: |
             python test_calculator.py
