update pielines with new changes 03

diff --git a/.github/workflows/duplo-commit.yaml b/.github/workflows/duplo-commit.yaml
--- a/.github/workflows/duplo-commit.yaml
+++ b/.github/workflows/duplo-commit.yaml
@@ -17,24 +17,28 @@ jobs:
         shell: bash
     steps:
       - uses: actions/checkout@v1
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-            python-version: 3.8
-      - name: Install dependencies
-        run: |
-            python3 -m pip install --upgrade pip
-            pip3 install pycodestyle
-      - name: python linting
-        run: |
-            pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 > pycodestyle_output.txt && echo -e "\033[32mLint Checking Passed\033[0m"
-            if [ -s pycodestyle_output.txt ]; then
-                echo "Pycodestyle errors found:"
-                cat pycodestyle_output.txt
-                exit 1
-            fi
+      # - name: Set up Python
+      #   uses: actions/setup-python@v2
+      #   with:
+      #       python-version: 3.8
+      # - name: Install dependencies
+      #   run: |
+      #       python3 -m pip install --upgrade pip
+      #       pip3 install pycodestyle
+      # - name: python linting
+      #   run: |
+      #       pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 > pycodestyle_output.txt && echo -e "\033[32mLint Checking Passed\033[0m"
+      #       if [ -s pycodestyle_output.txt ]; then
+      #           echo "Pycodestyle errors found:"
+      #           cat pycodestyle_output.txt
+      #           exit 1
+      #       fi
+      # - name: python unit tests
+      #   run: |
+      #       python test_calculator.py
+      #       echo "$GITHUB_CONTEXT"
       - name: python unit tests
         run: |
-            python test_calculator.py
-            echo "$GITHUB_CONTEXT"
+          python test_calculator.py
+          echo "${{github.event}}"
 
